login:
  username: admin
  password: admin

memory:
  maxFreeMemory: 128

queue:
  type: local
  size: 100000

executor:
  processor:
    corePoolSize: 3
    maxPoolSize: 10
    queueSize: 2000
  exporter:
    corePoolSize: 3
    maxPoolSize: 10
    queueSize: 2000
  resend.exporter:
    corePoolSize: 3
    maxPoolSize: 10
    queueSize: 2000

timing.data:
  domLoading: 500
  domInteractive: 500

exporter.batch:
  send:
    sendSize: 2
    sendTimeInMilliseconds: 20000
    retryTimes: 1
    url: http://127.0.0.1:8891/exporter/send
  resend:
    resendTimeInMilliseconds: 20000

logging:
  config: classpath:logback-spring.xml
  level:
    com.openrum: info

fail.backup:
    localPath: /data/openrum/backup
extension:
  monitor:
    intervalInMilliseconds: 30000




