login:
  username: admin
  password: admin

memory:
  maxFreeMemory: 128

queue:
  type: local
  size: 100000

executor:
  processor:
    corePoolSize: 3
    maxPoolSize: 10
    queueSize: 2000
  exporter:
    corePoolSize: 3
    maxPoolSize: 10
    queueSize: 2000
  resend.exporter:
    corePoolSize: 3
    maxPoolSize: 10
    queueSize: 2000

timing.data:
  domLoading: 500
  domInteractive: 500

exporter.send:
  batchSendSize: 2
  configTime: 0 0/3 * * * ?
  retryTimes: 1
  url: http://192.168.150.87:2222/receiver/send
  resendConfigTime: 0 0/1 * * * ?

logging:
  config: classpath:logback-spring.xml
  level:
    com.openrum: info

fail.backup:
    localPath: /data/openrum/backup



