login:
  username: admin
  password: admin

memory:
  maxFreeMemory: 128

queue:
  type: local
  size: 100000

executor:
  processor:
    corePoolSize: 3
    maxPoolSize: 10
    queueSize: 2000
  exporter:
    corePoolSize: 3
    maxPoolSize: 10
    queueSize: 2000

timing.data:
  domLoading: 500
  domInteractive: 500

sender.batch:
  batchSendSize: 10
  configTime: 200
  retryTimes: 3


logging:
  config: classpath:logback-spring.xml
  level:
    com.bonree.stm: info

