login:
  username: admin
  password: admin

memory:
  maxFreeMemory: 128

queue:
  type: local
  size: 100000

executor:
  processor:
    corePoolSize: 3
    maxPoolSize: 10
    queueSize: 2000
  exporter:
    corePoolSize: 3
    maxPoolSize: 10
    queueSize: 2000
  resend.exporter:
    corePoolSize: 3
    maxPoolSize: 10
    queueSize: 2000

timing.data:
  domLoading: 500
  domInteractive: 500

exporter.batch.send:
  sendSize: 2
  sendTimeInMilliseconds: 5000
  retryTimes: 1
  url: http://192.168.150.87:2222/receiver/send
  resendTimeInMilliseconds: 10000

logging:
  config: classpath:logback-spring.xml
  level:
    com.openrum: info

fail.backup:
    localPath: /data/openrum/backup



